services:
  windows:
    image: docker.arvancloud.ir/dockurr/windows
    container_name: windows
    environment:
      #VERSION: "http://192.168.43.163/iso/win11x64-enterprise-ltsc-eval.iso"   ###  Windows 11 LTS
      #VERSION: "http://192.168.43.163/iso/en-us_windows_10_enterprise_ltsc_2021_x64_dvd_d289cf96.iso" ## Windows 10 LTS 
      #VERSION: "http://192.168.43.163/iso/Win11EntLTSC_24H2.2033_x64_Compact.iso"   ## Windows 11 LTS Lite   NOT WORK
      VERSION: "http://192.168.43.163/iso/SW_DVD9_Win_Server_STD_CORE_2025_24H2_64Bit_English_DC_STD_MLF_X23-81891.ISO"  ## Windows 2025 Server
      RAM_SIZE: "6G"
      CPU_CORES: "4"
      REGION: "en-US"
      KEYBOARD: "en-US"    
      USERNAME: "Administrator"
      PASSWORD: "cluster"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - /opt/windows/:/storage
      - /opt/windows/data:/data
    deploy:
      resources:
        limits:
          memory: 7G
        reservations:
          memory: 6G

