version: '3'

services:
  asterisk:
    image: asterisk:16.2
    container_name: asterisk 
    hostname: asterisk-pbx
    volumes:
      - "/opt/docker-sample/asterisk/asterisk-config:/etc/asterisk:rw"
      - "/opt/docker-sample/asterisk/log:/var/log/asterisk:rw"
    command:
      - /bin/bash
      - -c
      - |
        asterisk -f && asterisk -rx 'module load chan_sip.so'

    ports:
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "5038:5038"
      - "8088:8088"
      - "10000-10099:10000-10099/udp"       # RTP ports

    network_mode: host
