version: "3.9"
services:
  routeros:
    image: evilfreelancer/docker-routeros:latest
    container_name: mikrotik 
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
      - /dev/kvm
    ports:
      - "2222:22"
      #- "2323:23"
      - "8001:80"
      #- "5900:5900"
      #- "8728:8728"
      #- "8729:8729"
      - "1300:13000" 

