global:
    scrape_interval:     15s # By default, scrape targets every 15 seconds.
    evaluation_interval: 15s # By default, scrape targets every 15 seconds.
    external_labels:
          monitor: 'codelab-monitor'
     scrape_configs:
        - job_name: 'prometheus'
     scrape_interval: 5s
     # metrics_path defaults to '/metrics'
     # scheme defaults to 'http'.
     static_configs:
        - targets: ['localhost:9090']
        - job_name: "postgres"
     scrape_interval: "15s"
     static_configs:
          - targets: ['postgres:9187']
