apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-postgres
  template:
    metadata:
      labels:
        app: zabbix-postgres
    spec:
      containers:
      - name: zabbix-postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: "zabbix"
        - name: POSTGRES_USER
          value: "zabbix"
        - name: POSTGRES_PASSWORD
          value: "zabbix_pass"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: zabbix-postgres-pvc

