apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-frontend
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: zabbix-frontend 
  template:
    metadata:
      labels:
        app: zabbix-frontend 
    spec:
      containers:
      - name: zabbix-frontend 
        image: zabbix/zabbix-web-nginx-pgsql 
        env:
        - name: DB_SERVER_HOST 
          value: "zabbix-postgres" 
        - name: POSTGRES_USER 
          value: "zabbix" 
        - name: POSTGRES_PASSWORD 
          value: "zabbix_pass" 
        ports:
        - containerPort :80  

