version: '3'

services:
  tele:
    image: asterisk18:v1.0.1
    container_name: asterisk 
    network_mode: bridge                    
    ports:
      - "5060:5060/udp"                     
      - "5060:5060"                         
      - "10000-10099:10000-10099/udp"       
    environment:
      - HOSTNAME=asterisk
    volumes:
      - /opt/git/DevOps/asterisk/configuration:/etc/asterisk:ro

