version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:8.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=Aa@123456780
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.15.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - KIBANA_PASSWORD=cluster
    ports:
      - "15601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
