version: '3'

services:
  clickhouse:
    image: docker.arvancloud.ir/clickhouse/clickhouse-server
    volumes:
      - /Data/ClickHouse/data_dir:/var/lib/clickhouse
      #- /Data/ClickHouse/clickhouse_config.xml:/etc/clickhouse-server/config.xml
    container_name: clickhourse
    restart: unless-stopped
    ports:
      - "8002:9000"
      - "8123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_network

  grafana:
    image: docker.arvancloud.ir/grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'

networks:
  ch_network:
    driver: bridge
