---
all:
  hosts:
    master:
      ansible_host: 192.168.122.101 
    worker1:
      ansible_host: 192.168.122.102
    worker2:
      ansible_host: 192.168.122.103
    worker3:
      ansible_host: 192.168.122.104
    worker4:
      ansible_host: 192.168.122.105
  children:
    masters:
      hosts:
        master:
    workers:
      hosts:
        worker1:
        worker2:
        worker3:
        worker4:
    k8s_cluster:
      children:
        masters:
        workers:

