---
- name: Setup RKE2 cluster
  hosts: all
  become: yes
  roles:
    - common

- name: Setup RKE2 master
  hosts: masters
  become: yes
  roles:
    - master

- name: Setup RKE2 workers
  hosts: workers
  become: yes
  roles:
    - worker
