version: '3.8'

networks:
  zabbix-net:
    driver: bridge

services:
  postgres:
    image: postgres:14
    container_name: zabbix-postgres
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - zabbix-net

  zabbix-server-1:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server-1
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
    ports:
      - "10051:10051"
    networks:
      - zabbix-net

  zabbix-server-2:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server-2
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
    ports:
      - "10052:10051"
    networks:
      - zabbix-net

  zabbix-proxy-1:
    image: zabbix/zabbix-proxy-sqlite3:latest
    container_name: zabbix-proxy-1
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      ZBX_SERVER_HOST: zabbix-server-1
    ports:
      - "10053:10051"
    networks:
      - zabbix-net

  zabbix-proxy-2:
    image: zabbix/zabbix-proxy-sqlite3:latest
    container_name: zabbix-proxy-2
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      ZBX_SERVER_HOST: zabbix-server-2
    ports:
      - "10054:10051"
    networks:
      - zabbix-net

  nginx-loadbalancer:
    image: nginx:latest
    container_name: nginx-loadbalancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - zabbix-net

  zabbix-web-1:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web-1
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      ZBX_SERVER_HOST: nginx-loadbalancer # Pointing to load balancer for HA setup.
    ports:
      - "8081:8080"
    networks:
      - zabbix-net

  zabbix-web-2:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web-2
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      ZBX_SERVER_HOST: nginx-loadbalancer # Pointing to load balancer for HA setup.
    ports:
      - "8082:8080"
    networks:
      - zabbix-net

volumes:
  pgdata:


