---
- name: Install RKE2 server
  shell: curl -sfL https://get.rke2.io | sh -
  args:
    creates: /usr/local/bin/rke2
  environment:
    INSTALL_RKE2_VERSION: v1.28.3+rke2r1  # نسخه دلخواه RKE2 را تنظیم کنید

- name: Enable and start RKE2 server
  systemd:
    name: rke2-server
    enabled: yes
    state: started

- name: Wait for RKE2 server to be ready
  wait_for:
    path: /var/lib/rancher/rke2/server/node-token
    state: present
    timeout: 300

- name: Create kubeconfig directory
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copy kubeconfig
  copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
    remote_src: yes

- name: Fetch node token
  slurp:
    src: /var/lib/rancher/rke2/server/node-token
  register: node_token

- name: Save node token to localhost
  copy:
    content: "{{ node_token['content'] | b64decode }}"
    dest: /tmp/rke2_node_token
  delegate_to: localhost

