version: '3'
services:
  opensearch-node: 
    image: opensearchproject/opensearch:latest 
    container_name: opensearch-node
    environment:
      - bootstrap.memory_lock=true 
      - plugins.security.disabled=true
      - plugins.security.ssl.http.enabled=false" 
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" 
      - discovery.type=single-node  
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Cluster@76411 
    ulimits:
      memlock:
        soft: -1 
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
        #- ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml 
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net
  
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 25601:5601 
    expose:
      - "5601" 
    environment:
      - OPENSEARCH_HOSTS= "http://opensearch-node:9200"
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD= Cluster@76411
    networks:
      - opensearch-net
    #volumes:
      #- ./opensearch-dashboard.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml

volumes:
  opensearch-data1:

networks:
  opensearch-net:


