  logstash:
    image: logstash:8.15.1
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash.conf:/usr/share/logstash/logstash.conf:ro,Z
    ports:
      - 514:514/udp
      - 5044:5044
      - 5000:5000/tcp
      - 5000:5000/udp
      - 9800:9600
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: Cluster@76411
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node1
    restart: unless-stopped
